version: "3.8"

services:

  landing-page:
    container_name: dev-landing-page
    image: ghcr.io/gamify-it/landing-page:main
    restart: always
    pull_policy: always
    expose:
      - "80"

  reverse-proxy:
    container_name: dev-reverse-proxy
    build: .
    restart: always
    environment:
      - DEPLOYMENT_NAME=dev
      - SSL_ENABLED=false
    ports:
      - "80:80"
